import 'earthquake_model.dart';
import 'help_request_model.dart';
import 'healthcare_model.dart';

class DummyData {
  static final List<EarthquakeModel> earthquakes = [
    EarthquakeModel(
      id: 'eq001',
      location: 'Sylhet',
      region: 'Sylhet Division',
      country: 'Bangladesh',
      magnitude: 6.1,
      depth: 12.4,
      latitude: 24.8949,
      longitude: 91.8687,
      time: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
      radiusKm: 85.0,
      casualties: 14,
      affected: 4200,
      isActive: true,
    ),
    EarthquakeModel(
      id: 'eq002',
      location: 'Chittagong',
      region: 'Chattogram Division',
      country: 'Bangladesh',
      magnitude: 5.3,
      depth: 18.7,
      latitude: 22.3569,
      longitude: 91.7832,
      time: DateTime.now().subtract(const Duration(hours: 8, minutes: 42)),
      radiusKm: 55.0,
      casualties: 2,
      affected: 870,
      isActive: true,
    ),
    EarthquakeModel(
      id: 'eq003',
      location: "Cox's Bazar",
      region: 'Chattogram Division',
      country: 'Bangladesh',
      magnitude: 4.8,
      depth: 24.2,
      latitude: 21.4272,
      longitude: 92.0058,
      time: DateTime.now().subtract(const Duration(hours: 15, minutes: 30)),
      radiusKm: 42.0,
      casualties: 0,
      affected: 310,
      isActive: false,
    ),
    EarthquakeModel(
      id: 'eq004',
      location: 'Mymensingh',
      region: 'Mymensingh Division',
      country: 'Bangladesh',
      magnitude: 4.2,
      depth: 30.1,
      latitude: 24.7471,
      longitude: 90.4203,
      time: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      radiusKm: 30.0,
      casualties: 0,
      affected: 120,
      isActive: false,
    ),
    EarthquakeModel(
      id: 'eq005',
      location: 'Rangamati',
      region: 'Chattogram Hill Tracts',
      country: 'Bangladesh',
      magnitude: 3.9,
      depth: 10.0,
      latitude: 22.6452,
      longitude: 92.1986,
      time: DateTime.now().subtract(const Duration(days: 2, hours: 7)),
      radiusKm: 22.0,
      casualties: 0,
      affected: 55,
      isActive: false,
    ),
    EarthquakeModel(
      id: 'eq006',
      location: 'Kathmandu',
      region: 'Bagmati Province',
      country: 'Nepal',
      magnitude: 7.2,
      depth: 8.5,
      latitude: 27.7172,
      longitude: 85.3240,
      time: DateTime.now().subtract(const Duration(days: 3, hours: 12)),
      radiusKm: 160.0,
      casualties: 89,
      affected: 28500,
      isActive: false,
    ),
  ];

  static final List<HelpRequestModel> helpRequests = [
    HelpRequestModel(
      id: 'hr001',
      name: 'Farhan Ahmed',
      avatarInitials: 'FA',
      type: HelpType.medical,
      description: 'Elderly parent injured, needs immediate medical assistance. Cannot move.',
      distanceKm: 0.8,
      address: '12 Mirpur Road, Dhaka',
      isUrgent: true,
      requestTime: DateTime.now().subtract(const Duration(minutes: 12)),
      status: HelpStatus.pending,
      peopleCount: 2,
      phone: '+880 1712-345678',
    ),
    HelpRequestModel(
      id: 'hr002',
      name: 'Nusrat Jahan',
      avatarInitials: 'NJ',
      type: HelpType.rescue,
      description: 'Family trapped under collapsed structure. 3 adults, 1 child.',
      distanceKm: 1.4,
      address: 'Block C, Pallabi, Dhaka',
      isUrgent: true,
      requestTime: DateTime.now().subtract(const Duration(minutes: 28)),
      status: HelpStatus.accepted,
      peopleCount: 4,
      phone: '+880 1812-456789',
    ),
    HelpRequestModel(
      id: 'hr003',
      name: 'Karim Uddin',
      avatarInitials: 'KU',
      type: HelpType.shelter,
      description: 'House severely damaged, family of 5 needs temporary shelter.',
      distanceKm: 2.1,
      address: 'Uttara Sector 7, Dhaka',
      isUrgent: false,
      requestTime: DateTime.now().subtract(const Duration(hours: 1, minutes: 10)),
      status: HelpStatus.pending,
      peopleCount: 5,
      phone: '+880 1912-567890',
    ),
    HelpRequestModel(
      id: 'hr004',
      name: 'Sumaiya Begum',
      avatarInitials: 'SB',
      type: HelpType.food,
      description: 'No food or clean water for 3 days since the earthquake.',
      distanceKm: 3.0,
      address: 'Demra, Dhaka',
      isUrgent: false,
      requestTime: DateTime.now().subtract(const Duration(hours: 2, minutes: 45)),
      status: HelpStatus.pending,
      peopleCount: 6,
      phone: '+880 1612-678901',
    ),
    HelpRequestModel(
      id: 'hr005',
      name: 'Rashed Khan',
      avatarInitials: 'RK',
      type: HelpType.water,
      description: 'Water supply disrupted. Community of ~30 people without clean water.',
      distanceKm: 4.5,
      address: 'Narsingdi Road, Dhaka',
      isUrgent: false,
      requestTime: DateTime.now().subtract(const Duration(hours: 5)),
      status: HelpStatus.pending,
      peopleCount: 30,
      phone: '+880 1512-789012',
    ),
    HelpRequestModel(
      id: 'hr006',
      name: 'Tanvir Islam',
      avatarInitials: 'TI',
      type: HelpType.medical,
      description: 'Need first aid supplies. Minor injuries in the neighborhood.',
      distanceKm: 5.2,
      address: 'Banani, Dhaka',
      isUrgent: false,
      requestTime: DateTime.now().subtract(const Duration(hours: 6, minutes: 20)),
      status: HelpStatus.resolved,
      peopleCount: 8,
      phone: '+880 1412-890123',
    ),
  ];

  static final List<HealthcareModel> healthcareFacilities = [
    HealthcareModel(
      id: 'hc001',
      name: 'Dhaka Medical College Hospital',
      type: FacilityType.hospital,
      distanceKm: 1.2,
      address: 'Bakshibazar, Dhaka 1000',
      isOpen: true,
      phone: '+880 2-55165088',
      availableBeds: 45,
      totalBeds: 2600,
      rating: 4.2,
      specialties: ['Emergency', 'Trauma', 'Surgery', 'ICU'],
      hasEmergency: true,
      operatingHours: '24/7',
    ),
    HealthcareModel(
      id: 'hc002',
      name: 'Square Hospital Limited',
      type: FacilityType.hospital,
      distanceKm: 2.8,
      address: '18/F Bir Uttam Qazi Nuruzzaman Sarak, West Panthapath, Dhaka',
      isOpen: true,
      phone: '+880 10616-10616',
      availableBeds: 18,
      totalBeds: 550,
      rating: 4.6,
      specialties: ['Cardiology', 'Neurology', 'Orthopedics', 'Emergency'],
      hasEmergency: true,
      operatingHours: '24/7',
    ),
    HealthcareModel(
      id: 'hc003',
      name: 'Impulse Hospital',
      type: FacilityType.clinic,
      distanceKm: 3.5,
      address: '304/E Tejgaon I/A, Dhaka 1208',
      isOpen: true,
      phone: '+880 2-58953901',
      availableBeds: 12,
      totalBeds: 80,
      rating: 4.0,
      specialties: ['General Medicine', 'Pediatrics', 'Gynecology'],
      hasEmergency: false,
      operatingHours: '8AM - 10PM',
    ),
    HealthcareModel(
      id: 'hc004',
      name: 'City Blood Bank',
      type: FacilityType.bloodBank,
      distanceKm: 4.1,
      address: 'Segunbagicha, Dhaka 1000',
      isOpen: true,
      phone: '+880 1711-000111',
      availableBeds: 0,
      totalBeds: 0,
      rating: 4.3,
      specialties: ['A+', 'B+', 'O+', 'AB+', 'A-', 'O-'],
      hasEmergency: false,
      operatingHours: '24/7',
    ),
    HealthcareModel(
      id: 'hc005',
      name: 'Apotheek Pharma',
      type: FacilityType.pharmacy,
      distanceKm: 0.5,
      address: 'Gulshan-1, Dhaka 1212',
      isOpen: true,
      phone: '+880 1988-123456',
      availableBeds: 0,
      totalBeds: 0,
      rating: 4.1,
      specialties: ['Prescription', 'OTC', 'Emergency Meds'],
      hasEmergency: false,
      operatingHours: '7AM - 12AM',
    ),
    HealthcareModel(
      id: 'hc006',
      name: 'National Institute of Traumatology',
      type: FacilityType.hospital,
      distanceKm: 5.7,
      address: 'Sher-E-Bangla Nagar, Dhaka 1207',
      isOpen: true,
      phone: '+880 2-55167052',
      availableBeds: 8,
      totalBeds: 500,
      rating: 3.9,
      specialties: ['Trauma', 'Orthopedics', 'Burn Unit', 'Spine'],
      hasEmergency: true,
      operatingHours: '24/7',
    ),
  ];

  static EarthquakeModel get latestEarthquake => earthquakes.first;

  static int get activeCount =>
      earthquakes.where((e) => e.isActive).length;

  static int get totalAffected =>
      earthquakes.fold(0, (sum, e) => sum + e.affected);

  static int get totalCasualties =>
      earthquakes.fold(0, (sum, e) => sum + e.casualties);

  static int get pendingHelp =>
      helpRequests.where((h) => h.status == HelpStatus.pending).length;
}
